/** URLs de imágenes (Unsplash). Sustituir por tus propias fotos en producción. */
export const images = {
  hero: "/images/hero-principal.png",
  howItWorks: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&q=80",
  productShirts: "/images/playeras/playeras-modelo-1.png",
  productHoodies: "/images/sudaderas/sudaderas-modelo-1.png",
  productCaps: "/images/gorras/gorras-modelo-2.png",
  production: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
  testimonials: "/images/testimonials.png",
  playerasHero: "/images/playeras/playeras-modelo-1.png",
  playerasColores: "/images/playeras/playeras-colores.png",
  playerasModelos: [
    "/images/playeras/playeras-modelo-1.png",
    "/images/playeras/playeras-modelo-2.png",
    "/images/playeras/playeras-modelo-3.png",
    "/images/playeras/playeras-modelo-4.png",
  ] as const,
  playerasFabric: "/images/playeras/playeras-colores.png",
  playerasPrint: "/images/playeras/playeras-serigrafia.png",
  playerasSerigrafia: "/images/playeras/playeras-serigrafia.png",
  playerasBordado: "/images/playeras/playeras-bordado.png",
  playerasDigital: "/images/playeras/playeras-digital.png",
  sudaderasHero: "/images/sudaderas/sudaderas-modelo-1.png",
  sudaderasColores: "/images/sudaderas/sudaderas-colores.png",
  sudaderasModelos: [
    "/images/sudaderas/sudaderas-modelo-1.png",
    "/images/sudaderas/sudaderas-modelo-2.png",
    "/images/sudaderas/sudaderas-modelo-3.png",
    "/images/sudaderas/sudaderas-modelo-5.png",
  ] as const,
  sudaderasTypes: "/images/sudaderas/sudaderas-colores.png",
  sudaderasMateriales: [
    { src: "/images/sudaderas/sudaderas-material-brushed-fleece.png", material: "Interior felpa cepillada (brushed fleece)", detail: "Acabado tipo velvet" },
    { src: "/images/sudaderas/sudaderas-material-french-terry-mix.png", material: "French Terry 85% algodón / 15% poliéster", detail: "Suave y resistente" },
    { src: "/images/sudaderas/sudaderas-material-french-terry-cotton.png", material: "French Terry 100% algodón", detail: "Máxima suavidad" },
    { src: "/images/sudaderas/sudaderas-material-velvet-blend.png", material: "Mezcla algodón con interior tipo velvet", detail: "Textura aterciopelada" },
  ] as const,
  gorrasHero: "/images/gorras/gorras-modelo-2.png",
  gorrasColores: "/images/gorras/gorras-modelo-1.png",
  gorrasModelos: [
    "/images/gorras/gorras-modelo-1.png",
    "/images/gorras/gorras-modelo-2.png",
    "/images/gorras/gorras-modelo-3.png",
    "/images/gorras/gorras-modelo-4.png",
  ] as const,
  gorrasEmbroidery: "/images/gorras/gorras-modelo-3.png",
  comoFunciona: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
  nosotros: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80",
  contacto: "/images/contacto.png",
  cotizar: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80",
  stepIdea: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80",
  stepSupplier: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=600&q=80",
  stepDelivery: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&q=80",
  serigrafia: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&q=80",
  bordado: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400&q=80",
  digital: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=400&q=80",
};
